export const FETCH_MERCH = 'FETCH_MERCH';
export const RECEIVE_MERCH = 'RECEIVE_MERCH';

export const FETCH_ONE = 'FETCH_ONE';
export const RECEIVE_ONE = 'RECEIVE_ONE';

export const FETCHING_CART = 'FETCHING_CART';
export const SEND_CART = 'SEND_CART';
export const RECEIVE_CART = 'RECEIVE_CART';

export const FETCH_SESSION = 'FETCH_SESSION';
export const RECEIVE_SESSION = 'RECEIVE_SESSION';

export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const FETCH_ONE_POST = 'FETCH_ONE_POST';
export const RECEIVE_ONE_POST = 'RECEIVE_ONE_POST';

export const RECEIVE_HOMEPAGE = 'RECEIVE_HOMEPAGE';
export const RECEIVE_ABOUT = 'RECEIVE_ABOUT';
